### ISSUE TITLE
PHP 7.1 error in Administration->Other->Calendar->Categories

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1177]
Tested on following demo: http://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Alpine_3.6_-_uses_php_7.1.29

Getting white screen of death at 'Administration->Other->Calendar->Categories' with following php error:
``````
[30-Oct-2017 18:45:22 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function postcalendar_admin_categories(), 1 passed in /var/www/localhost/htdocs/openemr/interface/main/calendar/includes/pnMod.php on line 637 and exactly 3 expected in /var/www/localhost/htdocs/openemr/interface/main/calendar/modules/PostCalendar/pnadmin.php:1472
Stack trace:
#0 /var/www/localhost/htdocs/openemr/interface/main/calendar/includes/pnMod.php(637): postcalendar_admin_categories(Array)
#1 /var/www/localhost/htdocs/openemr/interface/main/calendar/index.php(162): pnModFunc('PostCalendar', 'admin', 'categories')
#2 {main}
  thrown in /var/www/localhost/htdocs/openemr/interface/main/calendar/modules/PostCalendar/pnadmin.php on line 1472
``````

**Comment by bradymiller** [comment]
Have proposed fix here:
https://github.com/openemr/openemr/pull/1190

This is an odd one to test since it does not even throw a warning in PHP 7.0 , but is at least not causing any issues in 7.0. Will likely just commit it and see how it works on the Development PHP 7.1 demos.
If this works, then will do the same type of fix for issue at https://github.com/openemr/openemr/issues/1176

**Comment by bradymiller** [comment]
fixed
